-- CreateEnum
CREATE TYPE "ShippingStatus" AS ENUM ('NOT_CREATED', 'CREATED', 'AWB_ASSIGNED', 'PICKUP_SCHEDULED', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', 'EXCEPTION');

-- AlterTable
ALTER TABLE "Order" ADD COLUMN "shippingStatus" "ShippingStatus" NOT NULL DEFAULT 'NOT_CREATED',
ADD COLUMN "shiprocketOrderId" TEXT,
ADD COLUMN "shipmentId" TEXT,
ADD COLUMN "awbCode" TEXT,
ADD COLUMN "courierName" TEXT,
ADD COLUMN "trackingUrl" TEXT,
ADD COLUMN "shippedAt" TIMESTAMP(3),
ADD COLUMN "deliveredAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Product" ADD COLUMN "weightKg" DOUBLE PRECISION,
ADD COLUMN "lengthCm" DOUBLE PRECISION,
ADD COLUMN "breadthCm" DOUBLE PRECISION,
ADD COLUMN "heightCm" DOUBLE PRECISION;