import { NextResponse } from 'next/server'
import prisma from '@/lib/db'
import { verifyWebhookSignature } from '@/lib/razorpay'
import { PaymentStatus, SellerApplicationStatus, OrderStatus } from '@prisma/client'

export async function POST(req: Request) {
  try {
    const signature = req.headers.get('x-razorpay-signature')
    
    if (!signature) {
      return NextResponse.json({ error: "Missing signature" }, { status: 400 })
    }

    const rawBody = await req.text()
    
    // 1. Verify Webhook Signature
    const isValid = verifyWebhookSignature(rawBody, signature)
    if (!isValid) {
      return NextResponse.json({ error: "Invalid webhook signature" }, { status: 400 })
    }

    const event = JSON.parse(rawBody)
    const eventId = req.headers.get('x-razorpay-event-id') || event.id

    if (!eventId) {
      return NextResponse.json({ error: "Missing event ID" }, { status: 400 })
    }

    // 2. Webhook Idempotency Check
    const existingEvent = await prisma.webhookEvent.findUnique({
      where: { eventId }
    })

    if (existingEvent) {
      // Event already processed. But let's ensure the admin email didn't fail previously.
      if (event.event === 'payment.captured' || event.event === 'order.paid') {
        const payload = event.payload.payment.entity;
        const razorpayOrderId = payload.order_id;
        if (razorpayOrderId) {
          const payment = await prisma.payment.findUnique({ where: { razorpayOrderId } });
          if (payment && payment.orderId) {
            const { ensureAdminNotification } = await import('@/lib/email');
            await ensureAdminNotification(payment.orderId);
          }
        }
      }
      return NextResponse.json({ success: true, message: "Event already processed" })
    }

    // 3. Process the event based on type
    const payload = event.payload.payment.entity

    const txResult = await prisma.$transaction(async (tx) => {
      // Log event
      await tx.webhookEvent.create({
        data: {
          eventId: eventId,
          eventType: event.event,
          payload: JSON.stringify(payload),
        }
      })

      if (event.event === 'payment.captured' || event.event === 'order.paid') {
        const razorpayOrderId = payload.order_id
        const razorpayPaymentId = payload.id

        // Find payment
        const payment = await tx.payment.findUnique({
          where: { razorpayOrderId },
          include: { order: { include: { items: true } } }
        })

        if (!payment) {
          // If payment doesn't exist yet, we might be out of order, or it's not generated by our system.
          // Real apps might retry later or store it in a dead letter queue.
          return
        }

        if (payment.status === PaymentStatus.CAPTURED) {
          // Already handled by frontend verification, but ensure email was sent
          return { justCapturedOrderId: payment.orderId }
        }

        // --- Process SELLER ONBOARDING PAYMENT ---
        if (payment.type === 'SELLER_ONBOARDING' && payment.sellerId) {
          await tx.payment.update({
            where: { id: payment.id },
            data: { status: PaymentStatus.CAPTURED, razorpayPaymentId }
          })
          
          await tx.seller.update({
            where: { id: payment.sellerId },
            data: { applicationStatus: SellerApplicationStatus.UNDER_REVIEW }
          })
        }

        // --- Process CHECKOUT PAYMENT ---
        if (payment.type === 'CUSTOMER_ORDER' && payment.orderId && payment.order) {
          
          const paymentUpdateResult = await tx.payment.updateMany({
            where: { id: payment.id, status: PaymentStatus.PENDING },
            data: { status: PaymentStatus.CAPTURED, razorpayPaymentId }
          })

          if (paymentUpdateResult.count === 0) {
            // Already captured concurrently by frontend
            return { justCapturedOrderId: null }
          }

          // Stock was already reserved atomically during order creation.
          // No second decrement needed here.

          await tx.order.update({
            where: { id: payment.orderId },
            data: { status: OrderStatus.PAID, paymentStatus: PaymentStatus.CAPTURED }
          })

          return { justCapturedOrderId: payment.orderId }
        }
      } else if (event.event === 'payment.failed') {
        const razorpayOrderId = payload.order_id

        const payment = await tx.payment.findUnique({
          where: { razorpayOrderId },
          include: { order: { include: { items: true } } }
        })

        if (payment && payment.status === PaymentStatus.PENDING) {
          await tx.payment.update({
            where: { id: payment.id },
            data: { status: PaymentStatus.FAILED }
          })

          if (payment.orderId) {
            await tx.order.update({
              where: { id: payment.orderId },
              data: { paymentStatus: PaymentStatus.FAILED, status: OrderStatus.CANCELLED }
            })

            // Restore pre-reserved stock since payment failed
            if (payment.order) {
              for (const item of payment.order.items) {
                await tx.product.update({
                  where: { id: item.productId },
                  data: { stock: { increment: item.quantity } }
                })
              }
            }
          }
        }
      }
      return { justCapturedOrderId: null }
    })

    if (txResult?.justCapturedOrderId) {
      try {
        const { ensureAdminNotification } = await import('@/lib/email');
        await ensureAdminNotification(txResult.justCapturedOrderId);
      } catch (emailErr) {
        console.error("Failed to dynamically import email lib in webhook:", emailErr);
      }
    }

    return NextResponse.json({ success: true })
  } catch (error: any) {
    console.error("Webhook Error:", error)
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 })
  }
}
