import { NextResponse } from 'next/server'
import prisma from '@/lib/db'
import { verifyWebhookSignature } from '@/lib/razorpay'
import { PaymentStatus, SellerApplicationStatus, OrderStatus } from '@prisma/client'

export async function POST(req: Request) {
  try {
    const signature = req.headers.get('x-razorpay-signature')
    
    if (!signature) {
      return NextResponse.json({ error: "Missing signature" }, { status: 400 })
    }

    const rawBody = await req.text()
    
    // 1. Verify Webhook Signature
    const isValid = verifyWebhookSignature(rawBody, signature)
    if (!isValid) {
      return NextResponse.json({ error: "Invalid webhook signature" }, { status: 400 })
    }

    const event = JSON.parse(rawBody)
    const eventId = req.headers.get('x-razorpay-event-id') || event.id

    if (!eventId) {
      return NextResponse.json({ error: "Missing event ID" }, { status: 400 })
    }

    // 2. Webhook Idempotency Check
    const existingEvent = await prisma.webhookEvent.findUnique({
      where: { eventId }
    })

    if (existingEvent) {
      // We already processed this event successfully, return 200 immediately
      return NextResponse.json({ success: true, message: "Event already processed" })
    }

    // 3. Process the event based on type
    const payload = event.payload.payment.entity

    await prisma.$transaction(async (tx) => {
      // Log event
      await tx.webhookEvent.create({
        data: {
          eventId: eventId,
          eventType: event.event,
          payload: JSON.stringify(payload),
        }
      })

      if (event.event === 'payment.captured' || event.event === 'order.paid') {
        const razorpayOrderId = payload.order_id
        const razorpayPaymentId = payload.id

        // Find payment
        const payment = await tx.payment.findUnique({
          where: { razorpayOrderId },
          include: { order: { include: { items: true } } }
        })

        if (!payment) {
          // If payment doesn't exist yet, we might be out of order, or it's not generated by our system.
          // Real apps might retry later or store it in a dead letter queue.
          return
        }

        if (payment.status === PaymentStatus.SUCCESS) {
          return // Already handled by frontend verification
        }

        // --- Process SELLER ONBOARDING PAYMENT ---
        if (payment.type === 'SELLER_REGISTRATION' && payment.sellerId) {
          await tx.payment.update({
            where: { id: payment.id },
            data: { status: PaymentStatus.SUCCESS, razorpayPaymentId }
          })
          
          await tx.seller.update({
            where: { id: payment.sellerId },
            data: { applicationStatus: SellerApplicationStatus.UNDER_REVIEW }
          })
        }

        // --- Process CHECKOUT PAYMENT ---
        if (payment.type === 'ORDER_CHECKOUT' && payment.orderId && payment.order) {
          // We must do inventory deduction IF it wasn't done by the frontend
          for (const item of payment.order.items) {
            const product = await tx.product.findUnique({ where: { id: item.productId } })
            // Note: If a webhook is processing, and stock goes below zero, 
            // a robust system might trigger a refund if stock cannot be fulfilled.
            // For simplicity, we just decrement here assuming frontend handles primary path.
            if (product && product.stock >= item.quantity) {
              await tx.product.update({
                where: { id: item.productId },
                data: { stock: { decrement: item.quantity } }
              })
            }
          }

          await tx.payment.update({
            where: { id: payment.id },
            data: { status: PaymentStatus.SUCCESS, razorpayPaymentId }
          })

          await tx.order.update({
            where: { id: payment.orderId },
            data: { status: OrderStatus.PAID }
          })
        }
      } else if (event.event === 'payment.failed') {
        const razorpayOrderId = payload.order_id

        const payment = await tx.payment.findUnique({
          where: { razorpayOrderId }
        })

        if (payment && payment.status === PaymentStatus.PENDING) {
          await tx.payment.update({
            where: { id: payment.id },
            data: { status: PaymentStatus.FAILED }
          })
        }
      }
    })

    return NextResponse.json({ success: true })
  } catch (error: any) {
    console.error("Webhook Error:", error)
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 })
  }
}
